import type { FutureToolConfig, ToolConfig } from "@/types/tools";
import { KAGOJ_ICONS } from "@/components/kagoj-icons";

const IMAGE_ICON_TONE = "bg-transparent ring-0 shadow-none";
const SVG_ICON_TONE = "bg-blue-50 text-blue-600 ring-blue-100";

export const TOOLS: ToolConfig[] = [
  // --- CONVERT ---
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    slug: "/tools/pdf-to-jpg",
    description: "Turn every PDF page into a high-quality JPG image.",
    iconSrc: "/Icons/pdf-to-jpg.png",
    iconAlt: "PDF to JPG icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Convert",
    enabled: true,
    badge: "Convert",
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    slug: "/tools/pdf-to-png",
    description: "Convert PDF pages to PNG images with transparent backgrounds.",
    iconSrc: "/Icons/pdf-to-png.png",
    iconAlt: "PDF to PNG icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Convert",
    enabled: true,
    badge: "Convert",
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    slug: "/tools/image-to-pdf",
    description: "Convert JPG and PNG images into a single PDF document.",
    iconSrc: "/Icons/image-to-pdf.png",
    iconAlt: "Image to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Convert",
    enabled: true,
    badge: "Convert",
  },
  {
    id: "image-converter",
    name: "Image Converter",
    slug: "/tools/image-converter",
    description: "Convert images between JPG, PNG, and WebP in bulk.",
    icon: KAGOJ_ICONS.pdfToPng, // Reusing existing icon style for image conversion, or we can use a generic picture one if it existed. pdfToPng is fine as a fallback since it has a picture tile.
    iconToneClassName: SVG_ICON_TONE,
    category: "Convert",
    enabled: true,
    badge: "Images",
  },

  // --- ORGANIZE ---
  {
    id: "merge-pdf",
    name: "Merge PDF",
    slug: "/tools/merge-pdf",
    description: "Combine multiple PDFs into a single document.",
    iconSrc: "/Icons/merge-pdf.png",
    iconAlt: "Merge PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    slug: "/tools/split-pdf",
    description: "Extract pages from your PDF or split each page into a separate PDF.",
    iconSrc: "/Icons/split-pdf.png",
    iconAlt: "Split PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    slug: "/tools/rotate-pdf",
    description: "Rotate your PDF pages 90 or 180 degrees.",
    iconSrc: "/Icons/rotate-pdf.png",
    iconAlt: "Rotate PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    slug: "/tools/organize-pdf",
    description: "Sort, add, rotate, and delete pages from your PDF.",
    icon: KAGOJ_ICONS.organizePdf,
    iconToneClassName: SVG_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "extract-pages",
    name: "Extract Pages",
    slug: "/tools/extract-pages",
    description: "Get a new document containing only the desired pages.",
    icon: KAGOJ_ICONS.extractPages,
    iconToneClassName: SVG_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "delete-pages",
    name: "Delete Pages",
    slug: "/tools/delete-pages",
    description: "Remove unnecessary pages from your PDF.",
    icon: KAGOJ_ICONS.organizePdf, // using organize icon for delete as well, since there isn't a dedicated delete icon in KAGOJ_ICONS
    iconToneClassName: SVG_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },

  // --- EDIT ---
  {
    id: "page-numbers",
    name: "Page Numbers",
    slug: "/tools/page-numbers",
    description: "Add page numbers into PDFs with custom formatting.",
    icon: KAGOJ_ICONS.pageNumbers,
    iconToneClassName: SVG_ICON_TONE,
    category: "Edit",
    enabled: true,
    badge: "Edit",
  },
  {
    id: "watermark-pdf",
    name: "Watermark PDF",
    slug: "/tools/watermark-pdf",
    description: "Stamp an image or text over your PDF in seconds.",
    icon: KAGOJ_ICONS.watermarkPdf,
    iconToneClassName: SVG_ICON_TONE,
    category: "Edit",
    enabled: true,
    badge: "Edit",
  },
];

export const POPULAR_TOOLS = [
  "pdf-to-jpg",
  "merge-pdf",
  "split-pdf",
  "organize-pdf",
  "image-to-pdf",
  "watermark-pdf",
];

export const FUTURE_TOOLS: FutureToolConfig[] = [
  {
    id: "compress-pdf",
    name: "Compress PDF",
    category: "Optimize",
    description: "Reduce file size while keeping the document readable.",
    iconSrc: "/Icons/compress-pdf.png",
    iconAlt: "Compress PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    category: "Convert",
    description: "Convert PDFs into editable DOCX documents.",
    iconSrc: "/Icons/pdf-to-word.png",
    iconAlt: "PDF to Word icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    category: "Convert",
    description: "Turn PDF pages into editable presentation slides.",
    iconSrc: "/Icons/pdf-to-powerpoint.png",
    iconAlt: "PDF to PowerPoint icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    category: "Convert",
    description: "Extract PDF table data into editable spreadsheets.",
    iconSrc: "/Icons/pdf-to-excel.png",
    iconAlt: "PDF to Excel icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    category: "Convert",
    description: "Convert DOC and DOCX files into clean PDF documents.",
    iconSrc: "/Icons/word-to-pdf.png",
    iconAlt: "Word to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    category: "Convert",
    description: "Export presentation slides into shareable PDF files.",
    iconSrc: "/Icons/powerpoint-to-pdf.png",
    iconAlt: "PowerPoint to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    category: "Convert",
    description: "Save spreadsheet layouts as portable PDF documents.",
    iconSrc: "/Icons/excel-to-pdf.png",
    iconAlt: "Excel to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
];
