import type { FutureToolConfig, ToolConfig } from "@/types/tools";

const IMAGE_ICON_TONE = "bg-transparent ring-0 shadow-none";

export const TOOLS: ToolConfig[] = [
  // --- CONVERT ---
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    slug: "/tools/pdf-to-jpg",
    description: "Turn every PDF page into a high-quality JPG image.",
    iconSrc: "/Icons/pdf-to-jpg.png",
    iconAlt: "PDF to JPG icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Convert",
    enabled: true,
    badge: "Convert",
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    slug: "/tools/pdf-to-png",
    description: "Convert PDF pages to PNG images with transparent backgrounds.",
    iconSrc: "/Icons/pdf-to-png.png",
    iconAlt: "PDF to PNG icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Convert",
    enabled: true,
    badge: "Convert",
  },
  // --- IMAGES ---
  {
    id: "scan-to-pdf",
    name: "Scan to PDF",
    slug: "/tools/scan-to-pdf",
    description: "Scan documents with your camera and turn them into a clean multi-page PDF.",
    iconSrc: "/Icons/scan-to-pdf.png",
    iconAlt: "Scan to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Images",
    enabled: true,
    badge: "Images",
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    slug: "/tools/image-to-pdf",
    description: "Convert JPG and PNG images into a single PDF document.",
    iconSrc: "/Icons/image-to-pdf.png",
    iconAlt: "Image to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Images",
    enabled: true,
    badge: "Images",
  },
  {
    id: "image-converter",
    name: "Image Converter",
    slug: "/tools/image-converter",
    description: "Convert images between JPG, PNG, and WebP in bulk.",
    iconSrc: "/Icons/image-converter.png",
    iconAlt: "Image Converter icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Images",
    enabled: true,
    badge: "Images",
  },

  // --- ORGANIZE ---
  {
    id: "merge-pdf",
    name: "Merge PDF",
    slug: "/tools/merge-pdf",
    description: "Combine multiple PDFs into a single document.",
    iconSrc: "/Icons/merge-pdf.png",
    iconAlt: "Merge PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    slug: "/tools/split-pdf",
    description: "Extract pages from your PDF or split each page into a separate PDF.",
    iconSrc: "/Icons/split-pdf.png",
    iconAlt: "Split PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    slug: "/tools/rotate-pdf",
    description: "Rotate your PDF pages 90 or 180 degrees.",
    iconSrc: "/Icons/rotate-pdf.png",
    iconAlt: "Rotate PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    slug: "/tools/organize-pdf",
    description: "Sort, add, rotate, and delete pages from your PDF.",
    iconSrc: "/Icons/organize-pdf.png",
    iconAlt: "Organize PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "extract-pages",
    name: "Extract Pages",
    slug: "/tools/extract-pages",
    description: "Get a new document containing only the desired pages.",
    iconSrc: "/Icons/extract-pages.png",
    iconAlt: "Extract Pages icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },
  {
    id: "delete-pages",
    name: "Delete Pages",
    slug: "/tools/delete-pages",
    description: "Remove unnecessary pages from your PDF.",
    iconSrc: "/Icons/delete-pages.png",
    iconAlt: "Delete Pages icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },

  // --- EDIT ---
  {
    id: "page-numbers",
    name: "Page Numbers",
    slug: "/tools/page-numbers",
    description: "Add page numbers into PDFs with custom formatting.",
    iconSrc: "/Icons/page-numbers.png",
    iconAlt: "Page Numbers icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Edit",
    enabled: true,
    badge: "Edit",
  },
  {
    id: "watermark-pdf",
    name: "Watermark PDF",
    slug: "/tools/watermark-pdf",
    description: "Stamp an image or text over your PDF in seconds.",
    iconSrc: "/Icons/watermark-pdf.png",
    iconAlt: "Watermark PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Edit",
    enabled: true,
    badge: "Edit",
  },
  {
    id: "sign-pdf",
    name: "Sign PDF",
    slug: "/tools/sign-pdf",
    description: "Add your electronic signature to a PDF document.",
    iconSrc: "/Icons/sign-pdf.png",
    iconAlt: "Sign PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Edit",
    enabled: true,
    badge: "Edit",
  },
  {
    id: "edit-pdf",
    name: "Edit PDF",
    slug: "/tools/edit-pdf",
    description: "Add text, images, shapes, and signatures to your PDF.",
    iconSrc: "/Icons/edit-pdf.png",
    iconAlt: "Edit PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Edit",
    enabled: true,
    badge: "Edit",
  },
  {
    id: "fill-pdf",
    name: "Fill PDF",
    slug: "/tools/fill-pdf",
    description: "Fill out interactive PDF forms (AcroForms) quickly and securely.",
    iconSrc: "/Icons/fill-pdf.png",
    iconAlt: "Fill PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Edit",
    enabled: true,
    badge: "Edit",
  },

  // --- ORGANIZE (Continued) ---
  {
    id: "crop-pdf",
    name: "Crop PDF",
    slug: "/tools/crop-pdf",
    description: "Select an area to crop your PDF margins.",
    iconSrc: "/Icons/crop-pdf.png",
    iconAlt: "Crop PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Organize",
    enabled: true,
    badge: "Organize",
  },

  // --- SECURITY ---
  {
    id: "protect-pdf",
    name: "Protect PDF",
    slug: "/tools/protect-pdf",
    description: "Encrypt your PDF with a password.",
    iconSrc: "/Icons/protect-pdf.png",
    iconAlt: "Protect PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Security",
    enabled: true,
    badge: "Security",
  },
  {
    id: "unlock-pdf",
    name: "Unlock PDF",
    slug: "/tools/unlock-pdf",
    description: "Remove password protection from your PDF.",
    iconSrc: "/Icons/unlock-pdf.png",
    iconAlt: "Unlock PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Security",
    enabled: true,
    badge: "Security",
  },
  // --- OPTIMIZE ---
  {
    id: "compress-pdf",
    name: "Compress PDF",
    slug: "/tools/compress-pdf",
    description: "Reduce PDF file size while keeping your document readable.",
    iconSrc: "/Icons/compress-pdf.png",
    iconAlt: "Compress PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Optimize",
    enabled: true,
    badge: "Optimize",
  },
  {
    id: "ocr-pdf",
    name: "OCR PDF",
    slug: "/tools/ocr-pdf",
    description: "Recognize text in scanned PDFs and create searchable documents.",
    iconSrc: "/Icons/ocr-pdf.png",
    iconAlt: "OCR PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
    category: "Optimize",
    enabled: true,
    badge: "Optimize",
  },
];

export const POPULAR_TOOLS = [
  "merge-pdf",
  "compress-pdf",
  "pdf-to-jpg",
  "organize-pdf",
  "sign-pdf",
  "ocr-pdf",
];

export const FUTURE_TOOLS: FutureToolConfig[] = [
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    category: "Convert",
    description: "Convert PDFs into editable DOCX documents.",
    iconSrc: "/Icons/pdf-to-word.png",
    iconAlt: "PDF to Word icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    category: "Convert",
    description: "Turn PDF pages into editable presentation slides.",
    iconSrc: "/Icons/pdf-to-powerpoint.png",
    iconAlt: "PDF to PowerPoint icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    category: "Convert",
    description: "Extract PDF table data into editable spreadsheets.",
    iconSrc: "/Icons/pdf-to-excel.png",
    iconAlt: "PDF to Excel icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    category: "Convert",
    description: "Convert DOC and DOCX files into clean PDF documents.",
    iconSrc: "/Icons/word-to-pdf.png",
    iconAlt: "Word to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    category: "Convert",
    description: "Export presentation slides into shareable PDF files.",
    iconSrc: "/Icons/powerpoint-to-pdf.png",
    iconAlt: "PowerPoint to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
  {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    category: "Convert",
    description: "Save spreadsheet layouts as portable PDF documents.",
    iconSrc: "/Icons/excel-to-pdf.png",
    iconAlt: "Excel to PDF icon",
    iconToneClassName: IMAGE_ICON_TONE,
  },
];
