import {
  CompressPdfIcon,
  ExtractPagesIcon,
  ImageToPdfIcon,
  MergePdfIcon,
  OrganizePdfIcon,
  PageNumbersIcon,
  PdfToJpgIcon,
  PdfToPngIcon,
  ProtectPdfIcon,
  RotatePdfIcon,
  SplitPdfIcon,
  WatermarkIcon,
} from "@/components/kagoj-icons";
import { FutureToolConfig, ToolConfig } from "@/types/tools";

export const TOOLS: ToolConfig[] = [
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    slug: "/tools/pdf-to-jpg",
    description: "Turn every PDF page into a high-quality JPG image.",
    icon: PdfToJpgIcon,
    category: "Convert",
    enabled: true,
    iconToneClassName: "bg-blue-50 text-blue-600 ring-blue-100",
    badge: "Convert",
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    slug: "/tools/pdf-to-png",
    description: "Convert PDF pages to PNG images with transparent backgrounds.",
    icon: PdfToPngIcon,
    category: "Convert",
    enabled: true,
    iconToneClassName: "bg-cyan-50 text-cyan-600 ring-cyan-100",
    badge: "Convert",
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    slug: "/tools/image-to-pdf",
    description: "Convert JPG and PNG images into a single PDF document.",
    icon: ImageToPdfIcon,
    category: "Convert",
    enabled: true,
    iconToneClassName: "bg-indigo-50 text-indigo-600 ring-indigo-100",
    badge: "Convert",
  },
  {
    id: "merge-pdf",
    name: "Merge PDF",
    slug: "/tools/merge-pdf",
    description: "Combine multiple PDFs into a single document.",
    icon: MergePdfIcon,
    category: "Organize",
    enabled: true,
    iconToneClassName: "bg-violet-50 text-violet-600 ring-violet-100",
    badge: "Organize",
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    slug: "/tools/split-pdf",
    description: "Extract pages from your PDF or split each page into a separate PDF.",
    icon: SplitPdfIcon,
    category: "Organize",
    enabled: true,
    iconToneClassName: "bg-sky-50 text-sky-700 ring-sky-100",
    badge: "Organize",
  },
  {
    id: "rotate-pdf",
    name: "Rotate PDF",
    slug: "/tools/rotate-pdf",
    description: "Rotate your PDF pages 90 or 180 degrees.",
    icon: RotatePdfIcon,
    category: "Organize",
    enabled: true,
    iconToneClassName: "bg-teal-50 text-teal-600 ring-teal-100",
    badge: "Organize",
  },
];

export const POPULAR_TOOLS = ["pdf-to-jpg", "image-to-pdf", "merge-pdf", "split-pdf"];

export const FUTURE_TOOLS: FutureToolConfig[] = [
  {
    id: "compress-pdf",
    name: "Compress PDF",
    category: "Optimize",
    description: "Reduce file size while keeping the document readable.",
    icon: CompressPdfIcon,
    iconToneClassName: "bg-blue-50 text-blue-600 ring-blue-100",
  },
  {
    id: "watermark-pdf",
    name: "Watermark PDF",
    category: "Edit",
    description: "Add branded or ownership overlays to your pages.",
    icon: WatermarkIcon,
    iconToneClassName: "bg-violet-50 text-violet-600 ring-violet-100",
  },
  {
    id: "page-numbers",
    name: "Page Numbers",
    category: "Organize",
    description: "Add clean page numbering across the document.",
    icon: PageNumbersIcon,
    iconToneClassName: "bg-indigo-50 text-indigo-600 ring-indigo-100",
  },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    category: "Organize",
    description: "Reorder and tidy pages in a focused workspace.",
    icon: OrganizePdfIcon,
    iconToneClassName: "bg-sky-50 text-sky-700 ring-sky-100",
  },
  {
    id: "extract-pages",
    name: "Extract Pages",
    category: "Organize",
    description: "Pull selected pages into new standalone files.",
    icon: ExtractPagesIcon,
    iconToneClassName: "bg-cyan-50 text-cyan-600 ring-cyan-100",
  },
  {
    id: "protect-pdf",
    name: "Protect PDF",
    category: "Edit",
    description: "Add document protection controls for sensitive files.",
    icon: ProtectPdfIcon,
    iconToneClassName: "bg-teal-50 text-teal-700 ring-teal-100",
  },
];
